### ISSUE TITLE
Move download button

### ISSUE THREAD

**Issue by ArturHanusek** [codingcab/management.products.api#1973]
Tools > Stocktaking 

Move download button to modal, same as on Restocking Page

![Image](https://user-images.githubusercontent.com/11669178/222833129-754bd083-7a75-4a39-9bbd-5ed3a1c191f1.png)

![Image](https://user-images.githubusercontent.com/11669178/222833179-a8574a95-990b-4b2e-a3cd-8d95a1c1997c.png)

**Comment by rizkypujiraharja** [comment]
1. if the download button moved to the modal when the gear button clicked, won't the user be confused?
Is the download button for RECENT STOCKTAKES or STOCKTAKE SUGGESTIONS?

2. is it necessary to be able to filter sku to download STOCKTAKE SUGGESTIONS?

**Comment by ArturHanusek** [comment]
sorry, didn't see this comment

We keep exactly the same format of menu everywhere so user knows exactly where to look for this button. It simplifies the training, usage and support. 
Having single options button also simplifies and decluters interface, user only sees what he needs to and he knows exactly where to go if he needs anything else 

Yes, it should download stocktake suggestions
