### ISSUE TITLE
Beautify settings page 

### ISSUE THREAD

**Issue by ArturHanusek** [codingcab/management.products.api#435]
https://demo.products.management/settings

Sample look

![2021-06-22 14 14 41](https://user-images.githubusercontent.com/11669178/122923159-abf3bd00-d364-11eb-82de-61fb357e130d.jpg)

**Comment by Vue-Laravel-Dev** [comment]
Hi, Artur
This is Romain Cadarsi from upwork.com
I have fixed 435 issue but i couldn't push because of permission.
could you add me on your repository?
