### ISSUE TITLE
DPD Ireland Settings page

### ISSUE THREAD

**Issue by ArturHanusek** [codingcab/management.products.api#448]
http://demo.products.management/settings/dpd-ireland

Settings page should be similiar styling as
https://demo.products.management/settings/api

Should be able to add / remove DPD ireland record (table modules_dpd-ireland_configuration)

Max 1 record allowed in DB

token,user and password should not be displayed

**Comment by haiakbar** [comment]
Should I display the api_username field? In DpdIrelandConfigurationResource class, it was shown

**Comment by ArturHanusek** [comment]
> Should I display the api_username field? In DpdIrelandConfigurationResource class, it was shown

yes, username is the "account code" so should be displayed
